# Generated by Django 6.1 on 2026-09-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_2xl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='has_2xs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='has_l',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='has_m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='has_s',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='has_xl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='has_xs',
            field=models.BooleanField(default=False),
        ),
    ]
