# Generated by Django 6.1 on 2026-09-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
